---
language: "english"
query_language: "sparql"
dataset_path: "/Users/somov-od/Documents/phd/projects/CompGen/my_dataset/merged_dataset/merged_dataset_vol_4.5.json"
save_split_dir_path: "dataset/lcquad/tmcd_split"
load_compounds_from_file: False
save_parsed_compounds: True
alpha: 0.1